'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChangePassAdmin

    '''<summary>
    '''OldPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OldPass As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''NewPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewPass As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''RePass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RePass As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''ChangePass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangePass As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
End Class
