'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class iisstart

    '''<summary>
    '''lblLastLogDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastLogDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastLogTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastLogTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToday As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnWorksOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWorksOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlLeavedWorks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeavedWorks As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblLeavedWorksCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeavedWorksCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbShowWorks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbShowWorks As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvWorks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvWorks As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlLeavedCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeavedCases As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblLeavedCasesCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeavedCasesCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMessages As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCooperation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCooperation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCooperation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCooperation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvCooperationRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCooperationRequests As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlMoveCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMoveCase As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptMoveCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMoveCase As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlAllow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAllow As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAllowEntrance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowEntrance As Global.System.Web.UI.WebControls.Label
End Class
