'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Contracts

    '''<summary>
    '''indIntro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents indIntro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd32 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd33 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd34 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd35 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInd36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInd36 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblINd37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblINd37 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl38 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl39 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIntro_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIntro_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIntro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIntro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1_10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTypes2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypes2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb2_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb2_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl3_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl3_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl3_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl4_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl4_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl4_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl5_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl5_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl5_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl5_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl6_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl6_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl6_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl6_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl7_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl7_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl7_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl7_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl8_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl8_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl8_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl8_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl9_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl9_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl0_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl0_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl10_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl10_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl10_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl10_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl11_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl11_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl11_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl11_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl12_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl12_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl12_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl13_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl13_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl13_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl13_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl14_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl14_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl14_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl14_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl15_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl15_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl15_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl15_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl16_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl16_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl16_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl16_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl17_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl17_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl17_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl17_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl18_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl18_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl18_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl18_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl19_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl19_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl19_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl19_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl20_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl20_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl20_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl20_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl21_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl21_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl21_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl21_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl22_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl22_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl22_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl22_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl23_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl23_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl23_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl23_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl24_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl24_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl24_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl24_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl25_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl25_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl25_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl25_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl26_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl26_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl26_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl26_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl27_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl27_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl27_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl27_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl28_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl28_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl28_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl28_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl29_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl29_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl29_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl29_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl30_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl30_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl30_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl30_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl31_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl31_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl31_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl32_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl32_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl32_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl32_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl33_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl33_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl33_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl33_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl34_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl34_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl34_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl34_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl35_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl35_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl35_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl35_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl36_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl36_9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl37_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl37_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl37_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl37_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl38_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl38_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl38_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl38_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl39_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl39_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl39_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl39_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl40_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl40_0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl40_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl40_1 As Global.System.Web.UI.WebControls.Label
End Class
