'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Countries
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtnAzerbaijan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnAzerbaijan As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnArmenia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnArmenia As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnUzbekistan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnUzbekistan As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnUAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnUAE As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''hplIran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplIran As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lbtnTurkmenistan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnTurkmenistan As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnTurkey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnTurkey As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnChina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnChina As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnIraq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnIraq As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnKazakhstan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnKazakhstan As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnQatar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnQatar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblSwitzwerland control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSwitzwerland As Global.System.Web.UI.WebControls.LinkButton
End Class
