'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LegalPractices

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hplContracts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplContracts As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplLitigations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplLitigations As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplEnergy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplEnergy As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplInvestment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplInvestment As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplCompanies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplCompanies As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplTransportation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplTransportation As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplArbitration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplArbitration As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplIPLaw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplIPLaw As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplAffairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplAffairs As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplProperty As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplAdvice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplAdvice As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplFamilyLaw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplFamilyLaw As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplInheritance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplInheritance As Global.System.Web.UI.WebControls.HyperLink
End Class
